// Mock data for development and testing
// Contains 8 sample restaurants with full menus

import { Restaurant, MenuCategory } from '@/types';

export const mockRestaurants: Restaurant[] = [
  {
    id: 'rest_001',
    name: 'Pizza Paradise',
    description: 'Authentic Italian pizzas made with love. Fresh ingredients, traditional recipes, and a passion for great food.',
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=400&fit=crop',
    cuisine: ['Italian', 'Pizza'],
    rating: 4.7,
    reviewCount: 324,
    deliveryTime: '25-35 min',
    deliveryFee: 2.99,
    minimumOrder: 15.0,
    isOpen: true,
    address: '123 Main Street, Downtown',
  },
  {
    id: 'rest_002',
    name: 'Burger Barn',
    description: 'Gourmet burgers crafted with premium beef and creative toppings. Our patties are hand-formed daily.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&h=400&fit=crop',
    cuisine: ['American', 'Burgers', 'Fast Food'],
    rating: 4.5,
    reviewCount: 512,
    deliveryTime: '20-30 min',
    deliveryFee: 1.99,
    minimumOrder: 12.0,
    isOpen: true,
    address: '456 Oak Avenue',
  },
  {
    id: 'rest_003',
    name: 'Sushi Sensation',
    description: 'Fresh sushi and Japanese cuisine prepared by master chefs. Experience authentic flavors from Japan.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&h=400&fit=crop',
    cuisine: ['Japanese', 'Sushi'],
    rating: 4.8,
    reviewCount: 289,
    deliveryTime: '30-40 min',
    deliveryFee: 3.99,
    minimumOrder: 20.0,
    isOpen: true,
    address: '789 Cherry Lane',
  },
  {
    id: 'rest_004',
    name: 'Taco Fiesta',
    description: 'Vibrant Mexican street food with authentic recipes. Fresh salsas, homemade tortillas, and bold flavors.',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800&h=400&fit=crop',
    cuisine: ['Mexican'],
    rating: 4.4,
    reviewCount: 198,
    deliveryTime: '20-25 min',
    deliveryFee: 2.49,
    minimumOrder: 10.0,
    isOpen: true,
    address: '321 Sunset Boulevard',
  },
  {
    id: 'rest_005',
    name: 'Dragon Palace',
    description: 'Traditional Chinese cuisine with a modern twist. Wok-fired dishes, dim sum, and family recipes.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&h=400&fit=crop',
    cuisine: ['Chinese'],
    rating: 4.3,
    reviewCount: 267,
    deliveryTime: '25-35 min',
    deliveryFee: 2.99,
    minimumOrder: 15.0,
    isOpen: true,
    address: '567 Dragon Street',
  },
  {
    id: 'rest_006',
    name: 'Mediterranean Delight',
    description: 'Fresh and healthy Mediterranean dishes. Grilled meats, fresh salads, and homemade hummus.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=400&fit=crop',
    cuisine: ['Mediterranean', 'Healthy'],
    rating: 4.6,
    reviewCount: 156,
    deliveryTime: '30-40 min',
    deliveryFee: 3.49,
    minimumOrder: 18.0,
    isOpen: true,
    address: '890 Olive Garden Way',
  },
  {
    id: 'rest_007',
    name: 'Curry House',
    description: 'Aromatic Indian curries and tandoori specialties. Rich spices, naan breads, and vegetarian options.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=800&h=400&fit=crop',
    cuisine: ['Indian'],
    rating: 4.5,
    reviewCount: 234,
    deliveryTime: '35-45 min',
    deliveryFee: 2.99,
    minimumOrder: 15.0,
    isOpen: false,
    address: '234 Spice Road',
  },
  {
    id: 'rest_008',
    name: 'Sweet Tooth Bakery',
    description: 'Artisan desserts and baked goods. Fresh pastries, custom cakes, and decadent treats.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1517433670267-30f41c6f8d85?w=800&h=400&fit=crop',
    cuisine: ['Desserts'],
    rating: 4.9,
    reviewCount: 412,
    deliveryTime: '20-30 min',
    deliveryFee: 1.99,
    minimumOrder: 8.0,
    isOpen: true,
    address: '111 Sugar Lane',
  },
];

// Menu data for each restaurant
export const mockMenus: Record<string, MenuCategory[]> = {
  rest_001: [
    {
      id: 'cat_001_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_001_001',
          restaurantId: 'rest_001',
          name: 'Margherita Pizza',
          description: 'Fresh tomatoes, mozzarella, basil, and olive oil on our signature crust',
          price: 14.99,
          image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=300&h=200&fit=crop',
          categoryId: 'cat_001_pop',
          isAvailable: true,
          isPopular: true,
          calories: 850,
        },
        {
          id: 'item_001_002',
          restaurantId: 'rest_001',
          name: 'Pepperoni Supreme',
          description: 'Loaded with premium pepperoni, mozzarella, and our secret tomato sauce',
          price: 16.99,
          image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=300&h=200&fit=crop',
          categoryId: 'cat_001_pop',
          isAvailable: true,
          isPopular: true,
          calories: 920,
        },
      ],
    },
    {
      id: 'cat_001_pizza',
      name: '🍕 Pizzas',
      items: [
        {
          id: 'item_001_003',
          restaurantId: 'rest_001',
          name: 'Four Cheese',
          description: 'Mozzarella, parmesan, gorgonzola, and ricotta',
          price: 17.99,
          categoryId: 'cat_001_pizza',
          isAvailable: true,
          calories: 900,
        },
        {
          id: 'item_001_004',
          restaurantId: 'rest_001',
          name: 'BBQ Chicken',
          description: 'Grilled chicken, BBQ sauce, red onions, and cilantro',
          price: 18.99,
          categoryId: 'cat_001_pizza',
          isAvailable: true,
          calories: 880,
        },
        {
          id: 'item_001_005',
          restaurantId: 'rest_001',
          name: 'Veggie Delight',
          description: 'Bell peppers, mushrooms, olives, onions, and tomatoes',
          price: 15.99,
          categoryId: 'cat_001_pizza',
          isAvailable: true,
          calories: 720,
        },
      ],
    },
    {
      id: 'cat_001_sides',
      name: '🥗 Sides',
      items: [
        {
          id: 'item_001_006',
          restaurantId: 'rest_001',
          name: 'Garlic Breadsticks',
          description: 'Freshly baked with garlic butter and herbs (6 pcs)',
          price: 6.99,
          categoryId: 'cat_001_sides',
          isAvailable: true,
          calories: 320,
        },
        {
          id: 'item_001_007',
          restaurantId: 'rest_001',
          name: 'Caesar Salad',
          description: 'Romaine, parmesan, croutons, and Caesar dressing',
          price: 8.99,
          categoryId: 'cat_001_sides',
          isAvailable: true,
          calories: 280,
        },
      ],
    },
    {
      id: 'cat_001_drinks',
      name: '🥤 Drinks',
      items: [
        {
          id: 'item_001_008',
          restaurantId: 'rest_001',
          name: 'Soft Drink',
          description: 'Coca-Cola, Sprite, or Fanta',
          price: 2.49,
          categoryId: 'cat_001_drinks',
          isAvailable: true,
          calories: 140,
        },
        {
          id: 'item_001_009',
          restaurantId: 'rest_001',
          name: 'Italian Soda',
          description: 'Sparkling water with fruit syrup',
          price: 3.99,
          categoryId: 'cat_001_drinks',
          isAvailable: true,
          calories: 120,
        },
      ],
    },
  ],
  rest_002: [
    {
      id: 'cat_002_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_002_001',
          restaurantId: 'rest_002',
          name: 'Classic Cheeseburger',
          description: 'Angus beef patty, American cheese, lettuce, tomato, onion, pickles',
          price: 12.99,
          image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop',
          categoryId: 'cat_002_pop',
          isAvailable: true,
          isPopular: true,
          calories: 750,
        },
        {
          id: 'item_002_002',
          restaurantId: 'rest_002',
          name: 'Bacon BBQ Burger',
          description: 'Crispy bacon, cheddar, BBQ sauce, onion rings',
          price: 15.99,
          image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=300&h=200&fit=crop',
          categoryId: 'cat_002_pop',
          isAvailable: true,
          isPopular: true,
          calories: 920,
        },
      ],
    },
    {
      id: 'cat_002_burgers',
      name: '🍔 Burgers',
      items: [
        {
          id: 'item_002_003',
          restaurantId: 'rest_002',
          name: 'Mushroom Swiss',
          description: 'Sautéed mushrooms and melted Swiss cheese',
          price: 14.99,
          categoryId: 'cat_002_burgers',
          isAvailable: true,
          calories: 820,
        },
        {
          id: 'item_002_004',
          restaurantId: 'rest_002',
          name: 'Spicy Jalapeño',
          description: 'Pepper jack cheese, jalapeños, chipotle mayo',
          price: 14.99,
          categoryId: 'cat_002_burgers',
          isAvailable: true,
          calories: 800,
        },
        {
          id: 'item_002_005',
          restaurantId: 'rest_002',
          name: 'Veggie Burger',
          description: 'Plant-based patty with all the fixings',
          price: 13.99,
          categoryId: 'cat_002_burgers',
          isAvailable: true,
          calories: 580,
        },
      ],
    },
    {
      id: 'cat_002_sides',
      name: '🍟 Sides',
      items: [
        {
          id: 'item_002_006',
          restaurantId: 'rest_002',
          name: 'French Fries',
          description: 'Crispy golden fries with sea salt',
          price: 4.99,
          categoryId: 'cat_002_sides',
          isAvailable: true,
          calories: 380,
        },
        {
          id: 'item_002_007',
          restaurantId: 'rest_002',
          name: 'Onion Rings',
          description: 'Beer-battered and golden fried',
          price: 5.99,
          categoryId: 'cat_002_sides',
          isAvailable: true,
          calories: 420,
        },
        {
          id: 'item_002_008',
          restaurantId: 'rest_002',
          name: 'Loaded Fries',
          description: 'Fries with cheese, bacon, and sour cream',
          price: 7.99,
          categoryId: 'cat_002_sides',
          isAvailable: true,
          calories: 620,
        },
      ],
    },
  ],
  rest_003: [
    {
      id: 'cat_003_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_003_001',
          restaurantId: 'rest_003',
          name: 'Dragon Roll',
          description: 'Shrimp tempura, avocado, eel, and tobiko',
          price: 16.99,
          image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          categoryId: 'cat_003_pop',
          isAvailable: true,
          isPopular: true,
          calories: 480,
        },
        {
          id: 'item_003_002',
          restaurantId: 'rest_003',
          name: 'Rainbow Roll',
          description: 'California roll topped with assorted sashimi',
          price: 18.99,
          image: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=300&h=200&fit=crop',
          categoryId: 'cat_003_pop',
          isAvailable: true,
          isPopular: true,
          calories: 520,
        },
      ],
    },
    {
      id: 'cat_003_rolls',
      name: '🍣 Specialty Rolls',
      items: [
        {
          id: 'item_003_003',
          restaurantId: 'rest_003',
          name: 'Spicy Tuna Roll',
          description: 'Fresh tuna with spicy mayo and cucumber',
          price: 12.99,
          categoryId: 'cat_003_rolls',
          isAvailable: true,
          calories: 350,
        },
        {
          id: 'item_003_004',
          restaurantId: 'rest_003',
          name: 'California Roll',
          description: 'Crab, avocado, and cucumber',
          price: 10.99,
          categoryId: 'cat_003_rolls',
          isAvailable: true,
          calories: 320,
        },
        {
          id: 'item_003_005',
          restaurantId: 'rest_003',
          name: 'Philadelphia Roll',
          description: 'Smoked salmon, cream cheese, and cucumber',
          price: 13.99,
          categoryId: 'cat_003_rolls',
          isAvailable: true,
          calories: 380,
        },
      ],
    },
    {
      id: 'cat_003_nigiri',
      name: '🍱 Nigiri & Sashimi',
      items: [
        {
          id: 'item_003_006',
          restaurantId: 'rest_003',
          name: 'Salmon Nigiri (2 pcs)',
          description: 'Fresh Atlantic salmon over seasoned rice',
          price: 7.99,
          categoryId: 'cat_003_nigiri',
          isAvailable: true,
          calories: 180,
        },
        {
          id: 'item_003_007',
          restaurantId: 'rest_003',
          name: 'Tuna Sashimi (5 pcs)',
          description: 'Premium bluefin tuna slices',
          price: 14.99,
          categoryId: 'cat_003_nigiri',
          isAvailable: true,
          calories: 150,
        },
      ],
    },
  ],
  rest_004: [
    {
      id: 'cat_004_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_004_001',
          restaurantId: 'rest_004',
          name: 'Street Tacos (3)',
          description: 'Choice of carne asada, carnitas, or chicken with onion and cilantro',
          price: 10.99,
          image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300&h=200&fit=crop',
          categoryId: 'cat_004_pop',
          isAvailable: true,
          isPopular: true,
          calories: 450,
        },
        {
          id: 'item_004_002',
          restaurantId: 'rest_004',
          name: 'Burrito Bowl',
          description: 'Rice, beans, protein, pico, guac, sour cream, and cheese',
          price: 12.99,
          image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=300&h=200&fit=crop',
          categoryId: 'cat_004_pop',
          isAvailable: true,
          isPopular: true,
          calories: 680,
        },
      ],
    },
    {
      id: 'cat_004_tacos',
      name: '🌮 Tacos',
      items: [
        {
          id: 'item_004_003',
          restaurantId: 'rest_004',
          name: 'Fish Tacos (2)',
          description: 'Beer-battered fish with cabbage slaw and chipotle crema',
          price: 11.99,
          categoryId: 'cat_004_tacos',
          isAvailable: true,
          calories: 420,
        },
        {
          id: 'item_004_004',
          restaurantId: 'rest_004',
          name: 'Al Pastor Tacos (3)',
          description: 'Marinated pork with pineapple, onion, and cilantro',
          price: 11.99,
          categoryId: 'cat_004_tacos',
          isAvailable: true,
          calories: 480,
        },
      ],
    },
    {
      id: 'cat_004_burritos',
      name: '🌯 Burritos',
      items: [
        {
          id: 'item_004_005',
          restaurantId: 'rest_004',
          name: 'Classic Burrito',
          description: 'Giant flour tortilla stuffed with your choice of protein and toppings',
          price: 11.99,
          categoryId: 'cat_004_burritos',
          isAvailable: true,
          calories: 720,
        },
        {
          id: 'item_004_006',
          restaurantId: 'rest_004',
          name: 'Quesadilla',
          description: 'Grilled tortilla with melted cheese and protein',
          price: 9.99,
          categoryId: 'cat_004_burritos',
          isAvailable: true,
          calories: 580,
        },
      ],
    },
    {
      id: 'cat_004_sides',
      name: '🥑 Sides',
      items: [
        {
          id: 'item_004_007',
          restaurantId: 'rest_004',
          name: 'Chips & Guacamole',
          description: 'Fresh-made guacamole with crispy tortilla chips',
          price: 6.99,
          categoryId: 'cat_004_sides',
          isAvailable: true,
          calories: 380,
        },
        {
          id: 'item_004_008',
          restaurantId: 'rest_004',
          name: 'Mexican Rice',
          description: 'Seasoned rice with tomato and herbs',
          price: 3.99,
          categoryId: 'cat_004_sides',
          isAvailable: true,
          calories: 220,
        },
      ],
    },
  ],
  rest_005: [
    {
      id: 'cat_005_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_005_001',
          restaurantId: 'rest_005',
          name: 'General Tso Chicken',
          description: 'Crispy chicken in sweet and spicy sauce with broccoli',
          price: 14.99,
          image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=300&h=200&fit=crop',
          categoryId: 'cat_005_pop',
          isAvailable: true,
          isPopular: true,
          calories: 780,
        },
        {
          id: 'item_005_002',
          restaurantId: 'rest_005',
          name: 'Kung Pao Shrimp',
          description: 'Wok-tossed shrimp with peanuts, peppers, and chili sauce',
          price: 16.99,
          categoryId: 'cat_005_pop',
          isAvailable: true,
          isPopular: true,
          calories: 620,
        },
      ],
    },
    {
      id: 'cat_005_mains',
      name: '🥡 Main Dishes',
      items: [
        {
          id: 'item_005_003',
          restaurantId: 'rest_005',
          name: 'Beef with Broccoli',
          description: 'Tender beef slices stir-fried with fresh broccoli',
          price: 15.99,
          categoryId: 'cat_005_mains',
          isAvailable: true,
          calories: 580,
        },
        {
          id: 'item_005_004',
          restaurantId: 'rest_005',
          name: 'Sweet and Sour Pork',
          description: 'Crispy pork with pineapple in tangy sauce',
          price: 14.99,
          categoryId: 'cat_005_mains',
          isAvailable: true,
          calories: 720,
        },
        {
          id: 'item_005_005',
          restaurantId: 'rest_005',
          name: 'Mongolian Beef',
          description: 'Crispy beef with scallions in savory sauce',
          price: 16.99,
          categoryId: 'cat_005_mains',
          isAvailable: true,
          calories: 680,
        },
      ],
    },
    {
      id: 'cat_005_noodles',
      name: '🍜 Noodles & Rice',
      items: [
        {
          id: 'item_005_006',
          restaurantId: 'rest_005',
          name: 'Lo Mein',
          description: 'Soft noodles stir-fried with vegetables',
          price: 12.99,
          categoryId: 'cat_005_noodles',
          isAvailable: true,
          calories: 520,
        },
        {
          id: 'item_005_007',
          restaurantId: 'rest_005',
          name: 'Fried Rice',
          description: 'Wok-fried rice with egg, vegetables, and choice of protein',
          price: 11.99,
          categoryId: 'cat_005_noodles',
          isAvailable: true,
          calories: 480,
        },
      ],
    },
  ],
  rest_006: [
    {
      id: 'cat_006_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_006_001',
          restaurantId: 'rest_006',
          name: 'Chicken Shawarma Plate',
          description: 'Marinated chicken with hummus, rice, salad, and pita',
          price: 15.99,
          image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=300&h=200&fit=crop',
          categoryId: 'cat_006_pop',
          isAvailable: true,
          isPopular: true,
          calories: 680,
        },
        {
          id: 'item_006_002',
          restaurantId: 'rest_006',
          name: 'Falafel Wrap',
          description: 'Crispy falafel with tahini, pickles, and vegetables',
          price: 11.99,
          categoryId: 'cat_006_pop',
          isAvailable: true,
          isPopular: true,
          calories: 520,
        },
      ],
    },
    {
      id: 'cat_006_plates',
      name: '🍽️ Plates',
      items: [
        {
          id: 'item_006_003',
          restaurantId: 'rest_006',
          name: 'Lamb Kebab Plate',
          description: 'Grilled lamb skewers with rice and salad',
          price: 18.99,
          categoryId: 'cat_006_plates',
          isAvailable: true,
          calories: 720,
        },
        {
          id: 'item_006_004',
          restaurantId: 'rest_006',
          name: 'Mixed Grill',
          description: 'Chicken, lamb, and beef kebabs with all sides',
          price: 22.99,
          categoryId: 'cat_006_plates',
          isAvailable: true,
          calories: 850,
        },
      ],
    },
    {
      id: 'cat_006_mezze',
      name: '🥙 Mezze',
      items: [
        {
          id: 'item_006_005',
          restaurantId: 'rest_006',
          name: 'Hummus',
          description: 'Creamy chickpea dip with olive oil and pita',
          price: 6.99,
          categoryId: 'cat_006_mezze',
          isAvailable: true,
          calories: 280,
        },
        {
          id: 'item_006_006',
          restaurantId: 'rest_006',
          name: 'Baba Ganoush',
          description: 'Smoky eggplant dip with tahini and pita',
          price: 7.99,
          categoryId: 'cat_006_mezze',
          isAvailable: true,
          calories: 240,
        },
        {
          id: 'item_006_007',
          restaurantId: 'rest_006',
          name: 'Greek Salad',
          description: 'Tomatoes, cucumbers, olives, feta, and olive oil',
          price: 8.99,
          categoryId: 'cat_006_mezze',
          isAvailable: true,
          calories: 320,
        },
      ],
    },
  ],
  rest_007: [
    {
      id: 'cat_007_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_007_001',
          restaurantId: 'rest_007',
          name: 'Butter Chicken',
          description: 'Tender chicken in creamy tomato-butter sauce',
          price: 16.99,
          image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=300&h=200&fit=crop',
          categoryId: 'cat_007_pop',
          isAvailable: true,
          isPopular: true,
          calories: 720,
        },
        {
          id: 'item_007_002',
          restaurantId: 'rest_007',
          name: 'Lamb Biryani',
          description: 'Fragrant basmati rice with spiced lamb and saffron',
          price: 18.99,
          categoryId: 'cat_007_pop',
          isAvailable: true,
          isPopular: true,
          calories: 780,
        },
      ],
    },
    {
      id: 'cat_007_curries',
      name: '🍛 Curries',
      items: [
        {
          id: 'item_007_003',
          restaurantId: 'rest_007',
          name: 'Chicken Tikka Masala',
          description: 'Grilled chicken in spiced tomato cream sauce',
          price: 16.99,
          categoryId: 'cat_007_curries',
          isAvailable: true,
          calories: 680,
        },
        {
          id: 'item_007_004',
          restaurantId: 'rest_007',
          name: 'Palak Paneer',
          description: 'Fresh spinach curry with cottage cheese',
          price: 14.99,
          categoryId: 'cat_007_curries',
          isAvailable: true,
          calories: 520,
        },
        {
          id: 'item_007_005',
          restaurantId: 'rest_007',
          name: 'Dal Makhani',
          description: 'Creamy black lentils slow-cooked overnight',
          price: 12.99,
          categoryId: 'cat_007_curries',
          isAvailable: true,
          calories: 480,
        },
      ],
    },
    {
      id: 'cat_007_breads',
      name: '🫓 Breads',
      items: [
        {
          id: 'item_007_006',
          restaurantId: 'rest_007',
          name: 'Garlic Naan',
          description: 'Tandoor-baked bread with garlic and butter',
          price: 3.99,
          categoryId: 'cat_007_breads',
          isAvailable: true,
          calories: 280,
        },
        {
          id: 'item_007_007',
          restaurantId: 'rest_007',
          name: 'Cheese Naan',
          description: 'Naan stuffed with melted cheese',
          price: 4.99,
          categoryId: 'cat_007_breads',
          isAvailable: true,
          calories: 380,
        },
      ],
    },
  ],
  rest_008: [
    {
      id: 'cat_008_pop',
      name: '🔥 Popular',
      items: [
        {
          id: 'item_008_001',
          restaurantId: 'rest_008',
          name: 'Chocolate Lava Cake',
          description: 'Warm chocolate cake with molten center and vanilla ice cream',
          price: 8.99,
          image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=300&h=200&fit=crop',
          categoryId: 'cat_008_pop',
          isAvailable: true,
          isPopular: true,
          calories: 580,
        },
        {
          id: 'item_008_002',
          restaurantId: 'rest_008',
          name: 'New York Cheesecake',
          description: 'Classic creamy cheesecake with berry compote',
          price: 7.99,
          categoryId: 'cat_008_pop',
          isAvailable: true,
          isPopular: true,
          calories: 520,
        },
      ],
    },
    {
      id: 'cat_008_cakes',
      name: '🎂 Cakes',
      items: [
        {
          id: 'item_008_003',
          restaurantId: 'rest_008',
          name: 'Red Velvet Slice',
          description: 'Moist red velvet with cream cheese frosting',
          price: 6.99,
          categoryId: 'cat_008_cakes',
          isAvailable: true,
          calories: 480,
        },
        {
          id: 'item_008_004',
          restaurantId: 'rest_008',
          name: 'Tiramisu',
          description: 'Italian coffee-soaked ladyfingers with mascarpone',
          price: 7.99,
          categoryId: 'cat_008_cakes',
          isAvailable: true,
          calories: 420,
        },
      ],
    },
    {
      id: 'cat_008_pastries',
      name: '🥐 Pastries',
      items: [
        {
          id: 'item_008_005',
          restaurantId: 'rest_008',
          name: 'Croissant',
          description: 'Buttery, flaky French pastry',
          price: 3.99,
          categoryId: 'cat_008_pastries',
          isAvailable: true,
          calories: 280,
        },
        {
          id: 'item_008_006',
          restaurantId: 'rest_008',
          name: 'Cinnamon Roll',
          description: 'Fresh-baked with cream cheese glaze',
          price: 4.99,
          categoryId: 'cat_008_pastries',
          isAvailable: true,
          calories: 420,
        },
        {
          id: 'item_008_007',
          restaurantId: 'rest_008',
          name: 'Chocolate Éclair',
          description: 'Choux pastry filled with cream and topped with chocolate',
          price: 5.99,
          categoryId: 'cat_008_pastries',
          isAvailable: true,
          calories: 380,
        },
      ],
    },
    {
      id: 'cat_008_drinks',
      name: '☕ Beverages',
      items: [
        {
          id: 'item_008_008',
          restaurantId: 'rest_008',
          name: 'Hot Chocolate',
          description: 'Rich Belgian chocolate with whipped cream',
          price: 4.99,
          categoryId: 'cat_008_drinks',
          isAvailable: true,
          calories: 320,
        },
        {
          id: 'item_008_009',
          restaurantId: 'rest_008',
          name: 'Milkshake',
          description: 'Thick and creamy - chocolate, vanilla, or strawberry',
          price: 5.99,
          categoryId: 'cat_008_drinks',
          isAvailable: true,
          calories: 480,
        },
      ],
    },
  ],
};

// Mock users for testing
export const mockUsers = {
  customer: {
    id: 'usr_001',
    email: 'customer@test.com',
    password: 'password123',
    name: 'John Doe',
    role: 'customer' as const,
    phone: '+1234567890',
    createdAt: '2024-01-15T10:30:00Z',
  },
  admin: {
    id: 'usr_002',
    email: 'admin@test.com',
    password: 'admin123',
    name: 'Admin User',
    role: 'admin' as const,
    phone: '+1987654321',
    createdAt: '2024-01-01T00:00:00Z',
  },
};

// Mock orders for testing
export const mockOrders = [
  {
    id: 'ord_001',
    userId: 'usr_001',
    restaurantId: 'rest_001',
    restaurantName: 'Pizza Paradise',
    restaurantImage: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=100&h=100&fit=crop',
    items: [
      { id: 'oi_001', menuItemId: 'item_001_001', name: 'Margherita Pizza', price: 14.99, quantity: 2 },
      { id: 'oi_002', menuItemId: 'item_001_006', name: 'Garlic Breadsticks', price: 6.99, quantity: 1 },
    ],
    status: 'delivered' as const,
    subtotal: 36.97,
    tax: 2.96,
    deliveryFee: 2.99,
    total: 42.92,
    deliveryAddress: {
      street: '123 Customer Lane',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
    },
    paymentMethod: 'card_4242',
    createdAt: '2024-01-18T12:30:00Z',
    updatedAt: '2024-01-18T13:15:00Z',
    statusHistory: [
      { status: 'pending' as const, timestamp: '2024-01-18T12:30:00Z' },
      { status: 'confirmed' as const, timestamp: '2024-01-18T12:32:00Z' },
      { status: 'preparing' as const, timestamp: '2024-01-18T12:35:00Z' },
      { status: 'ready' as const, timestamp: '2024-01-18T12:55:00Z' },
      { status: 'out_for_delivery' as const, timestamp: '2024-01-18T13:00:00Z' },
      { status: 'delivered' as const, timestamp: '2024-01-18T13:15:00Z' },
    ],
  },
  {
    id: 'ord_002',
    userId: 'usr_001',
    restaurantId: 'rest_002',
    restaurantName: 'Burger Barn',
    restaurantImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=100&h=100&fit=crop',
    items: [
      { id: 'oi_003', menuItemId: 'item_002_002', name: 'Bacon BBQ Burger', price: 15.99, quantity: 1 },
      { id: 'oi_004', menuItemId: 'item_002_006', name: 'French Fries', price: 4.99, quantity: 2 },
    ],
    status: 'preparing' as const,
    subtotal: 25.97,
    tax: 2.08,
    deliveryFee: 1.99,
    total: 30.04,
    deliveryAddress: {
      street: '123 Customer Lane',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
    },
    paymentMethod: 'card_4242',
    createdAt: '2024-01-20T18:30:00Z',
    updatedAt: '2024-01-20T18:35:00Z',
    estimatedDelivery: '2024-01-20T19:15:00Z',
    statusHistory: [
      { status: 'pending' as const, timestamp: '2024-01-20T18:30:00Z' },
      { status: 'confirmed' as const, timestamp: '2024-01-20T18:32:00Z' },
      { status: 'preparing' as const, timestamp: '2024-01-20T18:35:00Z' },
    ],
  },
];

export default {
  restaurants: mockRestaurants,
  menus: mockMenus,
  users: mockUsers,
  orders: mockOrders,
};
